# Generated by Django 5.0.3 on 2024-08-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potentiala_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.CharField(default='no description', max_length=100),
            preserve_default=False,
        ),
    ]
