# Generated by Django 5.0.3 on 2024-08-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potentiala_1', '0002_work_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='description',
        ),
    ]
